apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "octopodAppAuthSecretName" . }}'
  labels:
    {{- include "octopod.labels" . | nindent 4 }}
data:
  auth: {{ htpasswd "octopod" (include "octopodAppAuthPassword" . ) | b64enc }}

