[package]
name = "web-app"
version = "0.1.0"
authors = ["Typeable <octopod@typeable.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.0"
actix-rt = "1.1.1"
askama = "0.10.5"
